defaults: &defaults
  adapter: postgis
  encoding: unicode
  pool: 5
  postgis_extension: postgis,postgis_topology
  schema_search_path: public,topology

development:
  database: new-block-city_development
  <<: *defaults

test:
  database: new-block-city_test
  <<: *defaults

production:
  database: new-block-city_production
  <<: *defaults
