development:
  adapter: postgis
  encoding: unicode
  database: new-block-city_development
  pool: 5
  postgis_extension: true
  schema_search_path: public,postgis

test:
  adapter: postgis
  encoding: unicode
  database: new-block-city_test
  pool: 5
  postgis_extension: true
  schema_search_path: public,postgis

production:
  adapter: postgis
  encoding: unicode
  database: new-block-city_production
  pool: 5
  postgis_extension: true
  schema_search_path: public,postgis
