default: &defaults
  access_key: 406a5b5620af84ed047d
  secret_key: 7f61ad2af3115f2fd56c
  cloud_id: 08f3efa18618adc397c31694f941afcf

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  cloud_id: c77acabd8dd0b1fa0bc7eb3ec6519bd9
